image: node:latest

stages:
  - lint
    
cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

lint:
  stage: lint
  script:
    - pnpm install
    - pnpm lint